In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
#NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

a3 =  np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
        
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ] 
])

In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1

array([1, 2, 3])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
# Create a Dataframe from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Creating arrays

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10 , size= (3,5))
random_array

array([[2, 6, 7, 7, 2],
       [9, 7, 2, 4, 6],
       [5, 1, 8, 6, 9]])

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [29]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.81459636, 0.59331428, 0.16734524],
       [0.18767153, 0.25892835, 0.98669712],
       [0.23300616, 0.12343643, 0.91623996],
       [0.99655006, 0.68591767, 0.48573125],
       [0.92716617, 0.01487571, 0.13309791]])

In [30]:
random_array_2.shape

(5, 3)

In [31]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.67966259, 0.59613994, 0.83594407],
       [0.3130644 , 0.76942825, 0.36404387],
       [0.39489192, 0.10762265, 0.69899309],
       [0.24448565, 0.8129901 , 0.65405603],
       [0.5274647 , 0.79122036, 0.1608792 ]])

In [32]:
# Pseudo-random numbers
np.random.seed(seed=42)
random_array_4 = np.random.randint(10, size= (5,3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [33]:
random_array_4.shape

(5, 3)

In [34]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [35]:
# np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3. Viewing arrays and matrices

In [36]:
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 9])

In [37]:
a1

array([1, 2, 3])

In [38]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [40]:
a1[0]

np.int64(1)

In [41]:
a2.shape

(2, 3)

In [42]:
a2[1]

array([4, 5, 6])

In [43]:
a3.shape

(2, 3, 3)

In [44]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a2[1]

array([4, 5, 6])

In [48]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [49]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [50]:
a3[0][0][1]

np.int64(2)

In [51]:
a1[:2]

array([1, 2])

In [52]:
a3.shape

(2, 3, 3)

In [53]:
# np.random.seed(seed=0)
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [54]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [55]:
# Get the first 4 numbers of the innermost arrays
a4[:,:,:,:4]
# a4[:,:,:,:2]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

In [56]:
a1[:4]

array([1, 2, 3])

## Manipulating & comparing arrays

### Arithmetic

In [57]:
a1

array([1, 2, 3])

In [58]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [59]:
a1 + ones

array([2., 3., 4.])

In [60]:
a1 - ones

array([0., 1., 2.])

In [61]:
a1 * ones

array([1., 2., 3.])

In [62]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [64]:
a1

array([1, 2, 3])

In [65]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [66]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 /ones

In [ ]:
a2 /a1

In [ ]:
# Floor division remove the decimals (rounds down)
a2 // a1

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1, ones)

In [ ]:
a1 + ones

In [ ]:
11 % 2

In [ ]:
a1 % 2

In [ ]:
a1

In [ ]:
a1 /2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

In [ ]:
a1

In [ ]:
np.exp(1)

In [ ]:
np.log(10)

### Aggregation
Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1

In [ ]:
type(a1)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

## Use Python's methods (`sum()`) on Python datatypes and use Numpy's methods on Numpy arrays(`np.sum()`).

In [ ]:
## Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy sum()

In [ ]:
17900 / 34

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.min(a2)

In [ ]:
np.max(a2)

In [ ]:
np.std(a2)

In [ ]:
np.var(a2)

In [ ]:
np.sqrt(np.var(a2))

In [ ]:
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
lower_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(high_var_array), np.var(lower_var_array)

In [ ]:
np.std(high_var_array), np.std(lower_var_array)

In [ ]:
np.mean(high_var_array), np.mean(lower_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(lower_var_array)
plt.show()

### Reshaping & transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a2.reshape(2, 3, 1).shape

In [ ]:
a2.reshape(2, 3, 1)

In [ ]:
a3.shape

In [ ]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
a2

In [ ]:
# Transpose
a2.T

In [ ]:
a2.T.shape


In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

## Dot product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))


mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
np.dot(mat1,mat2)

In [ ]:
# Transpose mat1
mat1.T

In [ ]:
mat1

In [ ]:
mat1.shape

In [ ]:
mat1.T.shape

In [ ]:
mat2.shape, mat1.T.shape

In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat2, mat1.T)
mat3

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

## Dot product (nut butter sales)

In [ ]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

In [ ]:
# Create weekly_sales Dataframe
weekly_sales = pd.DataFrame(sales_amounts, 
                            index=["Mon","Tue","Wed","Thurs","Fri"],
                            columns=["Almond butter","Peanut butter", "Cashew butter"]
                           )
weekly_sales

In [ ]:
# Create prices array
prices = np.array([12,8,12])
prices

In [ ]:
prices.shape

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"],
                            columns=["Almond butter","Peanut butter", "Cashew butter"] )
butter_prices

In [ ]:
sales_amounts.shape

In [ ]:
prices.shape

In [ ]:
total_sales = prices.dot()

In [ ]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

In [ ]:
sales_amounts

In [ ]:
weekly_sales.T, weekly_sales.T.shape, butter_prices.shape

In [ ]:
# Create daily_sales
butter_prices.shape, weekly_sales.T.shape

In [ ]:
butter_prices, weekly_sales.T 

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
# daily_sales = weekly_sales.dot(butter_prices.T)
daily_sales, type(daily_sales)

In [ ]:
weekly_sales

In [ ]:
butter_prices

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

In [ ]:
daily_sales.T.shape, weekly_sales.shape

In [ ]:
weekly_sales

### Comparison Operators

In [ ]:
a1.shape

In [ ]:
a3.shape

##  5. Sorting arrays

In [ ]:
random_array

In [ ]:
random_array = np.random.randint(10, size=(3,5 ))
random_array

In [ ]:
random_array.shape

In [ ]:
np.sort(random_array)

In [ ]:
random_array

In [ ]:
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [ ]:
random_array[4]

In [ ]:
np.argmin(a1)

In [ ]:
np.argmax(a1)

In [ ]:
np.argmax(random_array)

In [ ]:
random_array

In [ ]:
np.argmax(random_array, axis=0)

In [ ]:
np.argmax(random_array, axis=1)

In [ ]:
random_array.shape

In [ ]:
a1.shape

## Practical Example - NumPy in action!!!!

<img src="images/panda.png">

In [ ]:
# Turn an image into a Numy array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

In [ ]:
panda

In [ ]:
panda.size, panda.shape, panda.ndim

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2.shape

In [ ]:
custom_reshape = a3.reshape(2,3,3,1)
custom_reshape

In [ ]:
a3

In [ ]:
panda[:100]

<img src="images/car-photo.png" />

In [ ]:
car = imread("images/car-photo.png")
type(car)

In [ ]:
car[:1]

<img src="images/dog-photo.png"/>

In [ ]:
dog = imread("images/dog-photo.png")
type(dog)

In [ ]:
dog[:1]